spring.application.name=CruxConqueror
spring.datasource.url=jdbc:mysql://localhost:3306/crux_conqueror
spring.datasource.username=root
spring.datasource.password=40407039
spring.jpa.hibernate.ddl-auto=update
